name: Tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test:unit
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        env:
          BASE_URL: http://localhost:5555
          NODE_ENV: development
          DATABASE_USERNAME: ${{ twuf.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ twuf.DATABASE_PASSWORD }}
          DATABASE_URL: ${{ twuf.DATABASE_URL }}
          DATABASE_COLLECTION: ${{ twuf.DATABASE_COLLECTION }}
        with:
          build: yarn build
          config: baseUrl=http://localhost:5555,integrationFolder=e2e/__tests__,pluginsFile=e2e/plugins/index.js,videosFolder=e2e/videos,screenshotsFolder=e2e/screenshots,supportFile=false
          start: yarn start
          wait-on: http://localhost:5555